In [1]:
import requests
import pandas as pd

In [5]:
data = requests.get("https://data.police.uk/api/crimes-no-location?category=all-crime&date=2024-03&force=leicestershire")
data = data.json()
data = pd.DataFrame(data)
data

,category,location_type,location,context,outcome_status,persistent_id,id,location_subtype,month
0,bicycle-theft,None,None,,{'category': 'Investigation complete; no suspe...,8c1600035a8cc2e609b5de4e521d85a42d1ffe50447c25...,117354938,,2024-03
1,bicycle-theft,None,None,,{'category': 'Investigation complete; no suspe...,30bd820fa06ade936fa86de97b06c54f6d90a0a51b90f4...,117355868,,2024-03
2,bicycle-theft,None,None,,{'category': 'Investigation complete; no suspe...,217042b9946322e073907e32e2136069115020e4850526...,117351346,,2024-03
3,burglary,None,None,,{'category': 'Investigation complete; no suspe...,431a633ddcbe31decc329369055bf675a2ee423e9597e3...,117349047,,2024-03
4,burglary,None,None,,{'category': 'Investigation complete; no suspe...,a3346772bb4fb0cc64144729cd4d7f3b8aec7c0f40998a...,117357427,,2024-03
...,...,...,...,...,...,...,...,...,...
265,other-crime,None,None,,"{'category': 'Status update unavailable', 'dat...",1a1d749c96ce1dcb058f2a09780513c8b61a8a53711fdf...,117350258,,2024-03
266,other-crime,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",84443f73db02a7847d8735e53bd6e4f6555ab48553f1a5...,117347734,,2024-03
267,other-crime,None,None,,"{'category': 'Court result unavailable', 'date...",e02ac257bb357cd8339f4dc84149a5ff8789e5a0d28060...,117349660,,2024-03
268,other-crime,None,None,,{'category': 'Further action is not in the pub...,c23df25a60fdb5fed2dc8b25c98145866b4e0f00c7588c...,117356870,,2024-03
269,other-crime,None,None,,{'category': 'Investigation complete; no suspe...,d190b9da945da9077c39d89e42e0a641b2e9d25872a031...,117358161,,2024-03

In [8]:
data

          category                                     outcome_status
0    bicycle-theft  {'category': 'Investigation complete; no suspe...
1    bicycle-theft  {'category': 'Investigation complete; no suspe...
2    bicycle-theft  {'category': 'Investigation complete; no suspe...
3         burglary  {'category': 'Investigation complete; no suspe...
4         burglary  {'category': 'Investigation complete; no suspe...
..             ...                                                ...
265    other-crime  {'category': 'Status update unavailable', 'dat...
266    other-crime  {'category': 'Unable to prosecute suspect', 'd...
267    other-crime  {'category': 'Court result unavailable', 'date...
268    other-crime  {'category': 'Further action is not in the pub...
269    other-crime  {'category': 'Investigation complete; no suspe...

[270 rows x 2 columns]

In [12]:
categories = []
for status in data['outcome_status']:
    categories.append(status['category'])
    
print("categories: ", categories)
data['status'] = categories

categories:  ['Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Action to be taken by another organisation', 'Local resolution', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Court result unavailable', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Formal action is not in the public interest', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Offender given a caution', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Local resolution', 'Local resolution', 'Further action is not in the public interest', 'Local resolution', 'Local resolution', 'Local resolution', 'Court result unavailable', 'Status update unavailable', 'Action to be taken by another organisation', 'Court result unavailable', 'Formal action is not in the public interest', 'Local resolution', 'Local resolution', 'Local resolution', 'Investigation complete; no suspect identified', 'Further action is not in the public interest', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Local resolution', 'Unable to prosecute suspect', 'Offender given a caution', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Formal action is not in the public interest', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Offender given a caution', 'Investigation complete; no suspect identified', 'Further investigation is not in the public interest', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Formal action is not in the public interest', 'Local resolution', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Local resolution', 'Unable to prosecute suspect', 'Court result unavailable', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Court result unavailable', 'Further action is not in the public interest', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Court result unavailable', 'Unable to prosecute suspect', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Status update unavailable', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Local resolution', 'Unable to prosecute suspect', 'Court result unavailable', 'Court result unavailable', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Local resolution', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Local resolution', 'Court result unavailable', 'Local resolution', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Awaiting court outcome', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Action to be taken by another organisation', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Action to be taken by another organisation', 'Local resolution', 'Local resolution', 'Local resolution', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Court result unavailable', 'Status update unavailable', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Court result unavailable', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Action to be taken by another organisation', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Further action is not in the public interest', 'Status update unavailable', 'Unable to prosecute suspect', 'Action to be taken by another organisation', 'Action to be taken by another organisation', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Status update unavailable', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Further action is not in the public interest', 'Unable to prosecute suspect', 'Action to be taken by another organisation', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Status update unavailable', 'Court result unavailable', 'Status update unavailable', 'Unable to prosecute suspect', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Status update unavailable', 'Unable to prosecute suspect', 'Court result unavailable', 'Further action is not in the public interest', 'Investigation complete; no suspect identified']

In [14]:
stakeholder_data = data[
    (data['category']=='public-order') 
    & 
    (data['status']=="Unable to prosecute suspect")
    |
    (data['status'] == "Court result unavailable")
    ]
stakeholder_data

,category,outcome_status,status
20,criminal-damage-arson,"{'category': 'Court result unavailable', 'date...",Court result unavailable
41,drugs,"{'category': 'Court result unavailable', 'date...",Court result unavailable
44,drugs,"{'category': 'Court result unavailable', 'date...",Court result unavailable
62,possession-of-weapons,"{'category': 'Court result unavailable', 'date...",Court result unavailable
73,public-order,"{'category': 'Unable to prosecute suspect', 'd...",Unable to prosecute suspect
74,public-order,"{'category': 'Unable to prosecute suspect', 'd...",Unable to prosecute suspect
79,public-order,"{'category': 'Unable to prosecute suspect', 'd...",Unable to prosecute suspect
82,public-order,"{'category': 'Unable to prosecute suspect', 'd...",Unable to prosecute suspect
83,public-order,"{'category': 'Court result unavailable', 'date...",Court result unavailable
84,public-order,"{'category': 'Unable to prosecute suspect', 'd...",Unable to prosecute suspect
88,public-order,"{'category': 'Court result unavailable', 'date...",Court result unavailable
91,public-order,"{'category': 'Unable to prosecute suspect', 'd...",Unable to prosecute suspect
92,public-order,"{'category': 'Unable to prosecute suspect', 'd...",Unable to prosecute suspect
93,public-order,"{'category': 'Court result unavailable', 'date...",Court result unavailable
94,public-order,"{'category': 'Court result unavailable', 'date...",Court result unavailable
95,public-order,"{'category': 'Unable to prosecute suspect', 'd...",Unable to prosecute suspect
109,shoplifting,"{'category': 'Court result unavailable', 'date...",Court result unavailable
110,shoplifting,"{'category': 'Court result unavailable', 'date...",Court result unavailable
111,shoplifting,"{'category': 'Court result unavailable', 'date...",Court result unavailable
114,shoplifting,"{'category': 'Court result unavailable', 'date...",Court result unavailable
118,shoplifting,"{'category': 'Court result unavailable', 'date...",Court result unavailable
121,shoplifting,"{'category': 'Court result unavailable', 'date...",Court result unavailable
163,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
171,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
177,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
183,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
193,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
194,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
202,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
215,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
223,violent-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
260,other-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable
267,other-crime,"{'category': 'Court result unavailable', 'date...",Court result unavailable