In [30]:
import pandas as pd
import requests

In [31]:
crime_severity_data = pd.read_csv(r"data\crime_severity.csv")
crime_severity_data.head()

        category         id  severity offence_code
0  bicycle-theft  131028127         4        BT7K2
1  bicycle-theft  131027906         1        BT7K2
2  bicycle-theft  131028787         3        BT7K2
3       burglary  131032045         2        B9UR3
4       burglary  131025358         4        B9UR3

In [32]:
crime_severity_data =crime_severity_data[
    (crime_severity_data['category']=='public-order') 
     &(crime_severity_data['severity']>=2)
    ] 
crime_severity_data.head()

        category         id  severity offence_code
70  public-order  117344680         2        P0R9D
71  public-order  117355065         4        P0R9D
72  public-order  117345855         3        P0R9D
74  public-order  117347447         3        P0R9D
75  public-order  117357192         4        P0R9D

In [33]:
combined_data = requests.get("https://data.police.uk/api/crimes-no-location?category=all-crime&date=2024-03&force=leicestershire")
combined_data = combined_data.json()
combined_data= pd.DataFrame(combined_data)

categories = []
for status in combined_data['outcome_status']:
    categories.append(status['category'])
    
print("categories: ", categories)
combined_data['status'] = categories

combined_data = combined_data[
    (combined_data['category']=='public-order') 
    & 
    (combined_data['status']=="Unable to prosecute suspect")
    |
    (combined_data['status'] == "Court result unavailable")
    ]
combined_data

categories:  ['Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Action to be taken by another organisation', 'Local resolution', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Court result unavailable', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Formal action is not in the public interest', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Offender given a caution', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Local resolution', 'Local resolution', 'Further action is not in the public interest', 'Local resolution', 'Local resolution', 'Local resolution', 'Court result unavailable', 'Status update unavailable', 'Action to be taken by another organisation', 'Court result unavailable', 'Formal action is not in the public interest', 'Local resolution', 'Local resolution', 'Local resolution', 'Investigation complete; no suspect identified', 'Further action is not in the public interest', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Local resolution', 'Unable to prosecute suspect', 'Offender given a caution', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Formal action is not in the public interest', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Offender given a caution', 'Investigation complete; no suspect identified', 'Further investigation is not in the public interest', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Formal action is not in the public interest', 'Local resolution', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Local resolution', 'Unable to prosecute suspect', 'Court result unavailable', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Court result unavailable', 'Further action is not in the public interest', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Court result unavailable', 'Unable to prosecute suspect', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Status update unavailable', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Local resolution', 'Unable to prosecute suspect', 'Court result unavailable', 'Court result unavailable', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Local resolution', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Local resolution', 'Court result unavailable', 'Local resolution', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Awaiting court outcome', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Action to be taken by another organisation', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Action to be taken by another organisation', 'Local resolution', 'Local resolution', 'Local resolution', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Court result unavailable', 'Status update unavailable', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Court result unavailable', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Action to be taken by another organisation', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Further action is not in the public interest', 'Status update unavailable', 'Unable to prosecute suspect', 'Action to be taken by another organisation', 'Action to be taken by another organisation', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Status update unavailable', 'Court result unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Court result unavailable', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Further action is not in the public interest', 'Unable to prosecute suspect', 'Action to be taken by another organisation', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Investigation complete; no suspect identified', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Unable to prosecute suspect', 'Unable to prosecute suspect', 'Status update unavailable', 'Court result unavailable', 'Status update unavailable', 'Unable to prosecute suspect', 'Status update unavailable', 'Investigation complete; no suspect identified', 'Status update unavailable', 'Unable to prosecute suspect', 'Court result unavailable', 'Further action is not in the public interest', 'Investigation complete; no suspect identified']

,category,location_type,location,context,outcome_status,persistent_id,id,location_subtype,month,status
20,criminal-damage-arson,None,None,,"{'category': 'Court result unavailable', 'date...",6dfe1c4bc79e696b54d740fcc6417b63cecf3a66418f10...,117347993,,2024-03,Court result unavailable
41,drugs,None,None,,"{'category': 'Court result unavailable', 'date...",af46f752e74662729d55222d504d0de3de4297fba90c9a...,117351587,,2024-03,Court result unavailable
44,drugs,None,None,,"{'category': 'Court result unavailable', 'date...",b01b3618e4898a7b4c7b92a907ed66ecfaca70a31dd74f...,117345364,,2024-03,Court result unavailable
62,possession-of-weapons,None,None,,"{'category': 'Court result unavailable', 'date...",d629e9c34a5daf358373718724e3bd206edbcfc4010784...,117350974,,2024-03,Court result unavailable
73,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",030d91a505ec86d82617853f6a8e8742f34aa2b1f27839...,117352501,,2024-03,Unable to prosecute suspect
74,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",32018c0c11ec6f022a1060e43acdcaa1ade04c9efc4f89...,117349414,,2024-03,Unable to prosecute suspect
79,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",6892dcd8b5023dcad540780748701361997923c7b24ae4...,117345915,,2024-03,Unable to prosecute suspect
82,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",4455e84f5c41bab1c0d0afa223e6b96c329bb5376b32c9...,117344401,,2024-03,Unable to prosecute suspect
83,public-order,None,None,,"{'category': 'Court result unavailable', 'date...",4118d2f469c00a89f2c8cb28da36243a9fb5799ba441cd...,117345855,,2024-03,Court result unavailable
84,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",abcfb09ea84fa73a5c2a0ab8df94f40dd2fdc5bcdb1758...,117353950,,2024-03,Unable to prosecute suspect
88,public-order,None,None,,"{'category': 'Court result unavailable', 'date...",cd4307e893c2bd1ef52c78ad30d8c6576a4f0930552435...,117352865,,2024-03,Court result unavailable
91,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",40bbddb78e69a52ed60287127a6c5195965104339c13c8...,117355033,,2024-03,Unable to prosecute suspect
92,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",71493a6377fafa526e4e00dafb355022f34e64ae53a3a9...,117352174,,2024-03,Unable to prosecute suspect
93,public-order,None,None,,"{'category': 'Court result unavailable', 'date...",b214e10ead5a6695e76d91d8f02aa568ec366e94b0d7d0...,117351892,,2024-03,Court result unavailable
94,public-order,None,None,,"{'category': 'Court result unavailable', 'date...",be0eaf1c7f36ff24564d26d59e151bb2f0da171587ac24...,117347447,,2024-03,Court result unavailable
95,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",bd2b3e93e115d634b464483d8666ce34197f6b948423c4...,117352294,,2024-03,Unable to prosecute suspect
109,shoplifting,None,None,,"{'category': 'Court result unavailable', 'date...",669ae53ed29aac7f73701c67d524354563151147b78fce...,117346356,,2024-03,Court result unavailable
110,shoplifting,None,None,,"{'category': 'Court result unavailable', 'date...",92291b833ee4e5aeef7a84db153447aa6d9fd17d1012f9...,117346362,,2024-03,Court result unavailable
111,shoplifting,None,None,,"{'category': 'Court result unavailable', 'date...",0eda1a10664e871d71474663c37a2f0226af573ebb4a2b...,117346535,,2024-03,Court result unavailable
114,shoplifting,None,None,,"{'category': 'Court result unavailable', 'date...",70deea4a2a8d2d6c3aa3a1255300d3fda4fdc4b53e978e...,117347322,,2024-03,Court result unavailable
118,shoplifting,None,None,,"{'category': 'Court result unavailable', 'date...",be0f4531cc78dfac33e021d6a20417618051b05b657571...,117345327,,2024-03,Court result unavailable
121,shoplifting,None,None,,"{'category': 'Court result unavailable', 'date...",ffdfd0b3110cbb19825006a930f1f06337374b72ec1f89...,117359633,,2024-03,Court result unavailable
163,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",1d5633121a85b0d05b7e2ba6d5a79745b529219bc9e9f1...,117357868,,2024-03,Court result unavailable
171,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",17966b8dcde23e49b9a2685fbad569a9e5fc980fe0c861...,117359660,,2024-03,Court result unavailable
177,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",8b8ccf187fd6c79992e0d76a2bc75bc09c2861d415a245...,117353332,,2024-03,Court result unavailable
183,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",201f0147c7aa18b16228d8827981a9233f5f7a1961d123...,117359657,,2024-03,Court result unavailable
193,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",381fa6a9eab538e0fa7694a36551b8714a8948bd33755d...,117354596,,2024-03,Court result unavailable
194,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",789f92316c38cfe45158ba1c0d59d03cf2d4aaa6cf078c...,117354585,,2024-03,Court result unavailable
202,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",0c808e5ab25009a6fb6a69a9992edf85ba256c508ce7ec...,117351375,,2024-03,Court result unavailable
215,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",bb44a44fa5791ba12d8671e3a9257a7de195e01e9bc72c...,117347908,,2024-03,Court result unavailable
223,violent-crime,None,None,,"{'category': 'Court result unavailable', 'date...",239b78d69da9c5dffc8b1bd52e93447699b5a99fe37686...,117356781,,2024-03,Court result unavailable
260,other-crime,None,None,,"{'category': 'Court result unavailable', 'date...",25983d9ff306cca7b44091a30990c786f037736bd8da55...,117345372,,2024-03,Court result unavailable
267,other-crime,None,None,,"{'category': 'Court result unavailable', 'date...",e02ac257bb357cd8339f4dc84149a5ff8789e5a0d28060...,117349660,,2024-03,Court result unavailable

In [34]:
combined_data.set_index('id')
crime_severity_data.set_index('id')

               category  severity offence_code
id
117344680  public-order         2        P0R9D
117355065  public-order         4        P0R9D
117345855  public-order         3        P0R9D
117347447  public-order         3        P0R9D
117357192  public-order         4        P0R9D
117352174  public-order         2        P0R9D
117345558  public-order         4        P0R9D
117357494  public-order         3        P0R9D
117356063  public-order         3        P0R9D
117349414  public-order         4        P0R9D
117352294  public-order         2        P0R9D
117352603  public-order         4        P0R9D
117352724  public-order         3        P0R9D
117352832  public-order         4        P0R9D
117348089  public-order         3        P0R9D
117347983  public-order         2        P0R9D
117344667  public-order         3        P0R9D
117353950  public-order         4        P0R9D
117352774  public-order         2        P0R9D
117354630  public-order         4        P0R9D
117351892  public-order         3        P0R9D
117344641  public-order         2        P0R9D
117352865  public-order         3        P0R9D
117349302  public-order         4        P0R9D
117349181  public-order         2        P0R9D

In [35]:
data = pd.merge(combined_data, crime_severity_data, on='id')
data

,category_x,location_type,location,context,outcome_status,persistent_id,id,location_subtype,month,status,category_y,severity,offence_code
0,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",32018c0c11ec6f022a1060e43acdcaa1ade04c9efc4f89...,117349414,,2024-03,Unable to prosecute suspect,public-order,4,P0R9D
1,public-order,None,None,,"{'category': 'Court result unavailable', 'date...",4118d2f469c00a89f2c8cb28da36243a9fb5799ba441cd...,117345855,,2024-03,Court result unavailable,public-order,3,P0R9D
2,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",abcfb09ea84fa73a5c2a0ab8df94f40dd2fdc5bcdb1758...,117353950,,2024-03,Unable to prosecute suspect,public-order,4,P0R9D
3,public-order,None,None,,"{'category': 'Court result unavailable', 'date...",cd4307e893c2bd1ef52c78ad30d8c6576a4f0930552435...,117352865,,2024-03,Court result unavailable,public-order,3,P0R9D
4,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",71493a6377fafa526e4e00dafb355022f34e64ae53a3a9...,117352174,,2024-03,Unable to prosecute suspect,public-order,2,P0R9D
5,public-order,None,None,,"{'category': 'Court result unavailable', 'date...",b214e10ead5a6695e76d91d8f02aa568ec366e94b0d7d0...,117351892,,2024-03,Court result unavailable,public-order,3,P0R9D
6,public-order,None,None,,"{'category': 'Court result unavailable', 'date...",be0eaf1c7f36ff24564d26d59e151bb2f0da171587ac24...,117347447,,2024-03,Court result unavailable,public-order,3,P0R9D
7,public-order,None,None,,"{'category': 'Unable to prosecute suspect', 'd...",bd2b3e93e115d634b464483d8666ce34197f6b948423c4...,117352294,,2024-03,Unable to prosecute suspect,public-order,2,P0R9D

In [36]:
severity = []
for crime in data['severity']:
    if crime == 2:
        severity.append('low')
    elif crime == 3:
        severity.append('medium')
    elif crime == 4:
        severity.append('high')
data['sev-cat']=severity
data.to_csv("task_4_data.csv")