In [2]:
import pandas as pd

In [3]:
crime_severity_data = pd.read_csv(r"data\crime_severity.csv")
crime_severity_data.head()

        category         id  severity offence_code
0  bicycle-theft  131028127         4        BT7K2
1  bicycle-theft  131027906         1        BT7K2
2  bicycle-theft  131028787         3        BT7K2
3       burglary  131032045         2        B9UR3
4       burglary  131025358         4        B9UR3

In [4]:
stakeholder_data =crime_severity_data[
    (crime_severity_data['category']=='public-order') 
     &(crime_severity_data['severity']>=2)
    ] 
stakeholder_data.head()

        category         id  severity offence_code
70  public-order  117344680         2        P0R9D
71  public-order  117355065         4        P0R9D
72  public-order  117345855         3        P0R9D
74  public-order  117347447         3        P0R9D
75  public-order  117357192         4        P0R9D